### ISSUE TITLE
check_params fails on dynamic parameter updates

### ISSUE THREAD

**Issue by nitin194** [flennerhag/mlens#104]
First of all thank you so much for creating such an awesome package for stacking technique. I created a stack and used Superlearner to fit the input data. but received an error while trying to predict on the fitted model. Below is my code.

##################################
from mlens.ensemble import SuperLearner

sl = SuperLearner(
    folds=10,
    random_state=SEED,
    verbose=2,
    backend="multiprocessing"
)

sl.add(list(base_learners.values()), proba=True) 
sl.add_meta(meta_learner, proba=True)

sl.fit(xtrain, ytrain)

p_sl = sl.predict_proba(xtest)
##################################

The model was fitted properly, but below is the error I received while predicting on the test set.

##################################
~\AppData\Local\Continuum\Anaconda3\lib\site-packages\mlens\parallel\_base_functions.py in check_params(lpar, rpar)
       286     if isinstance(lpar, (int, float)):
       287         if np.isnan(lpar):
--> 288             _pass = np.isnan(rpar)
      289         elif np.isinf(lpar):
      290             _pass = np.isinf(rpar)

TypeError: ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
##################################

I tried several alternatives to mitigate this issue but no fate. Could you please help here?

**Comment by flennerhag** [comment]
Hi! 

It looks like you have a parameter in a base learner or meta learner that is of some unexpected data type. Can post a code for a complete minimal example that I can run?

Also, try installing the GitHub master branch (instead of the pip version). We’re just about to release a new version that so this might be fixed already.

**Comment by nitin194** [comment]
Hi @flennerhag,
Thank you for reverting back. PFA iPython notebook and the dataset. You can execute the whole notebook and the error will come itself at the end. Please let me know in case I need to share anything else?

[Stacking.zip](https://github.com/flennerhag/mlens/files/2463071/Stacking.zip)

**Comment by nitin194** [comment]
Hello @flennerhag 
Hope you are doing great. Were you able to check this one?

**Comment by flennerhag** [comment]
Hi, 

The culrpit is the meta learner, or rather XGB. When an XGB estimator is created, the ``missing`` parameter is ``None``. But during training this is changed to ``nan``, which violates how ``mlens`` checks parameters, as we assume constructor parameters are constant (an ``sklearn`` design paradigm).  

The parameter check functionality has proven problematic before, so it might have to be scrapped, but in the short-term you'll have to live with it. One option is to simply skip XGB for the time being, having a LightGBM estimator for instance should give you largely the effect. Another option is to clone the master branch, manually edit the file ``check_params`` function in the ``mlens/mlens/parallel/_base_functions.py`` file, and install locally. 

For instance, 

```python
def check_params(lpar, rpar):
    return True
```

would solve your issue. Note that this function is really just to make sure people don't accidentally change the ensemble without retraining so doing so isn't going to break anything.

I'll let you know when this has been fixed in the master.

**Comment by flennerhag** [comment]
Fixed as of #107 .
