### ISSUE TITLE
cant predict_prob

### ISSUE THREAD

**Issue by yanqiangmiffy** [flennerhag/mlens#109]
It only predict labels?the result of `predict_proba` and `predict` is same

**Comment by flennerhag** [comment]
``predict_proba`` is just for compatibility with Scikit-learn. Since we need to know up-front if we're going to fit the ensemble using probabilities or not, you must specify this in the ``add`` method when you construct the ensemble. You do this using the ``proba`` parameter. The [tutorial](http://ml-ensemble.com/info/tutorials/advanced.html#probabilistic-ensemble-learning) provides a more in-depth walk-through.

**Comment by flennerhag** [comment]
#108 might also be of help to you.
