### ISSUE TITLE
OSError: [Errno 24] Too many open files

### ISSUE THREAD

**Issue by joeybaba** [flennerhag/mlens#132]
macbook，
when i fit the data, error happen.

error still persist, after i set 'ulimit -n 4096'

**Comment by flennerhag** [comment]
Hi, 

It's hard to tell with such a generic description, but presumably, this happens because you're using memory mapping with too many cross-validation folds. You can try running with ``backend='threading'`` (this is the default) or try reducing the number of CV folds. In particular, you can run into this issue if you're using the subsemble method. An alternative is to set ``ulimit -n 30000`` or something such.
